name: Run Unit Tests
on:
  workflow_call

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d
        
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
          cache-dependency-path: package-lock.json
          
      - name: Build project
        run: npm install
        
      - name: Run NPM unit tests
        run: npm test
        
      - name: Run Ember Core Tests
        run: ./node_modules/ember-cli/bin/ember test
        
      - name: Run Ember Server tests
        run: ./node_modules/ember-cli/bin/ember test --server
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
